# Generated by Django 5.2.4 on 2025-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='Магазин', max_length=255),
        ),
    ]
